# Generated by Django 3.2.9 on 2023-09-22 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_create_super_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('reward_checkin_points', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.location')),
                ('tags', models.ManyToManyField(to='places.Tag')),
            ],
        ),
    ]
