name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

jobs:
  precommit:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.8.10
          architecture: x64
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Install Pre-commit
        run: pip install pre-commit==2.17.0
      - name: Run pre commit
        run: pre-commit run --all-files
      - name: Tear down the Stack
        run: make down-volumes

# With no caching at all the entire ci process takes 4m 30s to complete!
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Run tests with coverage
        run: make test
      - name: Tear down the Stack
        run: make down-volumes
      
  # bump:
  #   if: "github.event_name == 'push' && ( github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')"
  #   runs-on: ubuntu-20.04
  #   needs:
  #     - unittest
  #     - precommit
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@main
  #     - name: Install dependencies
  #       uses: actions/setup-node@v2.1.5
  #       with:
  #         node-version: '18.x'
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Release
  #       if: github.ref == 'refs/heads/main'
  #       env:
  #         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  #         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEM }}
  #       run: npx semantic-release
